"""Extended registry: every dataset named across the user's resource batches.

Generic verifier -> generates stream-source entries for whatever resolves.
Keeps the manual list small by covering each named family once.
"""

# (hf_id, config, split, field, domain)
EXTENDED = [
    # ==== comprehension: books / wiki / long-form ====
    ("HuggingFaceFW/finewiki", None, "train", "text", "wiki"),
    ("wikimedia/wikipedia", "20231101.zh", "train", "text", "wiki"),
    ("wikimedia/wikipedia", "20231101.en", "train", "text", "wiki"),
    ("wikimedia/wikipedia", "20231101.ja", "train", "text", "wiki"),
    ("wikimedia/wikipedia", "20231101.de", "train", "text", "wiki"),
    ("wikimedia/wikipedia", "20231101.fr", "train", "text", "wiki"),
    ("HuggingFaceTB/cosmopedia", "web_v1", "train", "text", "books"),
    ("HuggingFaceTB/cosmopedia", "stories", "train", "text", "books"),
    ("HuggingFaceTB/cosmopedia", "stanford", "train", "text", "textbook"),
    ("HuggingFaceTB/cosmopedia", "wikihow", "train", "text", "books"),
    ("HuggingFaceTB/cosmopedia", "openstax", "train", "text", "textbook"),
    ("sedthh/gutenberg_multilang", None, "train", "text", "books"),
    ("manu/project_gutenberg", None, "train", "text", "books"),
    ("HuggingFaceFW/fineweb", "sample-10BT", "train", "text", "web"),
    ("HuggingFaceFW/fineweb-edu", "sample-10BT", "train", "text", "web"),
    ("HuggingFaceTB/finemath", "finemath-4plus", "train", "text", "math"),
    ("PleIAs/common_corpus", None, "train", "text", "public_domain"),
    ("HuggingFaceTB/fineweb-2", "cmn_Hani", "train", "text", "web_zh"),
    ("HuggingFaceTB/fineweb-2", "eng_Latn", "train", "text", "web_en"),
    # ==== reasoning / math / cot ====
    ("open-thoughts/OpenThoughts2-1M", None, "train", "conversations", "reasoning"),
    ("AI-MO/NuminaMath-CoT", None, "train", "problem", "math"),
    ("AI-MO/NuminaMath-1.5", None, "train", "problem", "math"),
    ("nvidia/OpenMathReasoning", None, "train", "input", "math"),
    ("nvidia/OpenMathInstruct-2", None, "train", "problem", "math"),
    ("nvidia/Nemotron-Math", None, "train", "problem", "math"),
    ("TIGER-Lab/MathInstruct", None, "train", "instruction", "math"),
    ("open-r1/OpenR1-Math-220k", None, "train", "problem", "math"),
    ("bespokelabs/Bespoke-Stratos-17k", None, "train", "conversations", "reasoning"),
    ("PAI-2026/OmniThought", None, "train", "question", "reasoning"),
    ("microsoft/orca-math-word-problems-200k", None, "train", "question", "math"),
    ("meta-math/MetaMathQA", None, "train", "query", "math"),
    ("hendrycks/competition_math", None, "train", "problem", "math"),
    ("openai/gsm8k", "main", "train", "question", "math"),
    # ==== code ====
    ("nvidia/OpenCodeReasoning", None, "train", "input", "code"),
    ("nvidia/SWE-Zero2Hero", None, "train", "problem_statement", "code"),
    ("bigcode/the-stack-smol", None, "train", "content", "code"),
    ("codeparrot/codeparrot-clean", None, "train", "content", "code"),
    ("m-a-p/CodeFeedback-Filtered-Instruction", None, "train", "query", "code"),
    ("bigcode/stack-dedup-python", None, "train", "content", "code"),
    ("openai/openai_humaneval", None, "test", "prompt", "code"),
    ("sahil2801/CodeAlpaca-20k", None, "train", "instruction", "code"),
    ("iamtarun/python_code_instructions_18k_alpaca", None, "train", "instruction", "code"),
    # ==== multilingual ====
    ("CohereForAI/aya_collection", "aya_eng", "train", "inputs", "multilingual"),
    ("CohereForAI/aya_collection", "aya_zho", "train", "inputs", "multilingual"),
    ("MBZUAI/Bactrian-X", "zh", "train", "instruction", "multilingual"),
    ("MBZUAI/Bactrian-X", "en", "train", "instruction", "multilingual"),
    ("Helsinki-NLP/opus_books", "en-zh", "train", "translation", "parallel"),
    ("Helsinki-NLP/opus_books", "de-en", "train", "translation", "parallel"),
    ("Helsinki-NLP/opus-100", "en-zh", "train", "translation", "parallel"),
    ("facebook/flores", "eng_Latn-zho_Hans", "devtest", "sentence", "parallel"),
    ("allenai/nllb", "eng_Latn-zho_Hans", "train", "translation", "parallel"),
    # ==== domain: service / finance / legal / medical / ecom ====
    ("nguha/legalbench", None, "train", "text", "legal"),
    ("PolyAI/banking77", None, "train", "text", "banking"),
    ("clinc/clinc_oos", "plus", "train", "text", "intent"),
    ("bitext/Bitext-retail-banking-llm-chatbot-training-dataset", None, "train", "instruction", "banking"),
    ("FinGPT/fingpt-sentiment-train", None, "train", "input", "finance"),
    ("windone/FinCorpus", None, "train", "text", "finance"),
    ("disc-law-sft", None, "train", "input", "legal"),
    ("medalpaca/medical_meadow_medical_flashcards", None, "train", "input", "medical"),
    ("FreedomIntelligence/medical-o1-reasoning-SFT", "en", "train", "Question", "medical"),
    ("FreedomIntelligence/medical-o1-reasoning-SFT", "zh", "train", "Question", "medical"),
    ("Mihaiii/qa-assistant", None, "train", "input", "support"),
    ("mteb/amazon_massive_intent", "zh-CN", "train", "text", "intent"),
    ("amazon_reviews_multi", "zh", "train", "review_body", "ecom"),
    ("CarperAI/openai_summarize_tldr", None, "train", "prompt", "summarize"),
    # ==== decision / choice ====
    ("tasksource/100k-choice-dilemmas", None, "train", "question", "decision"),
    ("KRAFTON/Orak", None, "train", "text", "decision"),
    ("hails/bias-in-bios", None, "train", "raw", "decision"),
    # ==== instruction / general sft ====
    ("databricks/databricks-dolly-15k", None, "train", "instruction", "sft"),
    ("tatsu-lab/alpaca", None, "train", "instruction", "sft"),
    ("teknium/OpenHermes-2.5", None, "train", "conversations", "sft"),
    ("Open-Orca/OpenOrca", None, "train", "question", "sft"),
    ("HuggingFaceH4/ultrachat_200k", None, "train_sft", "messages", "sft"),
    ("allenai/tulu-3-sft-mixture", None, "train", "messages", "sft"),
    ("microsoft/orca-math-word-problems-200k", None, "train", "question", "math"),
    # ==== tool / shell / agent ====
    ("carosh/cli-1m", None, "train", "instruction", "shell"),
    ("glaiveai/glaive-function-calling-v2", None, "train", "chat", "tools"),
    ("Salesforce/xlam-function-calling-60k", None, "train", "query", "tools"),
    ("nebius/SWE-rebench", None, "train", "problem_statement", "code"),
    # ==== summarize / long context ====
    ("ccdv/cnn_dailymail", "3.0.0", "train", "article", "summarize"),
    ("abisee/cnn_dailymail", "3.0.0", "train", "article", "summarize"),
    ("EdinburghNLP/xsum", None, "train", "document", "summarize"),
    ("booksum", None, "train", "book", "long_context"),
    ("goyal/arxiv_dataset", None, "train", "abstract", "science"),
    ("scientific_papers", "arxiv", "train", "article", "science"),
]
